In [34]:
import numpy as np
import pandas as pd

In [35]:
data = pd.read_csv('preprocessing_year.csv', encoding='cp949')
least_idx=0
data.head()

Unnamed: 0   전출지별   전입지별  2017_x  2018_x  2019_x  2020_x  2021_x  \
0           0  부산광역시  서울특별시   19460   19737   20285   20990   20009   
1           1  부산광역시  대구광역시    4506    4505    4220    4674    4720   
2           2  부산광역시  인천광역시    2994    2902    3055    2980    2758   
3           3  부산광역시  광주광역시    1073    1011     992    1142    1139   
4           4  부산광역시  대전광역시    2159    2180    2172    2144    2124   

           거리        전입지 면적   2017_y   2018_y   2019_y   2020_y   2021_y  \
0  282.825019  6.052440e+08  9857426  9765623  9729107  9668465  9509458   
1   72.912774  8.836982e+08  2475231  2461769  2438031  2418346  2385412   
2  308.289734  1.066465e+09  2948542  2954642  2957026  2942828  2948375   
3  243.805183  5.011132e+08  1463770  1459336  1456468  1450062  1441611   
4  202.438173  5.395036e+08  1502227  1489936  1474870  1463882  1452251   

      2017     2018     2019     2020     2021  
0  3470653  3441453  3413841  3391946  3350380  
1  3470653  3441453  3413841  3391946  3350380  
2  3470653  3441453  3413841  3391946  3350380  
3  3470653  3441453  3413841  3391946  3350380  
4  3470653  3441453  3413841  3391946  3350380

In [36]:

alpha = 0.864852905
beta = 0.73614502
gamma = 0.941345215
sig = -10.58398438
lamb = 0
combinations = np.array(np.meshgrid(alpha,beta,gamma, sig, lamb)).T.reshape(-1,5)
combinations

array([[  0.86485291,   0.73614502,   0.94134522, -10.58398438,
          0.        ]])

In [37]:
tem = 1
tem *= np.exp(combinations[0,3])
tem *= (data['2017']**combinations[0,0])
tem *= (data['2017_y']**combinations[0,1]) 
tem /= (data['거리']**combinations[0,2]) 
tem *= np.exp(combinations[0,4] * data['2017_y'] / data['전입지 면적'] * data['거리'])

result = pd.DataFrame({
    'mig17' : data['2017_x'],
    'predict17' : tem
})
result.head()


mig17     predict17
0  19460   7954.762629
1   4506  10304.210328
2   2994   3016.665202
3   1073   2246.871795
4   2159   2728.245268

In [38]:

alpha = 0.838394165
beta = 0.752670288
gamma = 0.94744873
sig = -10.41601563
lamb = 0
combinations = np.array(np.meshgrid(alpha,beta,gamma, sig, lamb)).T.reshape(-1,5)
combinations

array([[  0.83839416,   0.75267029,   0.94744873, -10.41601563,
          0.        ]])

In [39]:
tem = 1
tem *= np.exp(combinations[least_idx,3])
tem *= (data['2018']**combinations[least_idx,0])
tem *= (data['2018_y']**combinations[least_idx,1]) 
tem /= (data['거리']**combinations[least_idx,2]) 
tem *= np.exp(combinations[least_idx,4] * data['2018_y'] / data['전입지 면적'] * data['거리'])

result['mig18']= data['2018_x']
result['predict18']=tem
result.head

<bound method NDFrame.head of      mig17     predict17  mig18     predict18
0    19460   7954.762629  19737   7852.358790
1     4506  10304.210328   4505  10054.005655
2     2994   3016.665202   2902   2942.684938
3     1073   2246.871795   1011   2161.343789
4     2159   2728.245268   2180   2618.268254
..     ...           ...    ...           ...
267  13179  13184.711862  11989  12370.369744
268  12426   8956.135944  11209   8399.980613
269  12464   9562.767887  12017   9020.467630
270  12692  10553.952408  11703  10015.934582
271  10404   2710.352757   9829   2533.526360

[272 rows x 4 columns]>

In [40]:

alpha = 0.835296631
beta = 0.811691284
gamma = 0.927429199
sig = -11.33398438
lamb = 0
combinations = np.array(np.meshgrid(alpha,beta,gamma, sig, lamb)).T.reshape(-1,5)
combinations

array([[  0.83529663,   0.81169128,   0.9274292 , -11.33398438,
          0.        ]])

In [41]:
tem = 1
tem *= np.exp(combinations[least_idx,3])
tem *= (data['2019']**combinations[least_idx,0])
tem *= (data['2019_y']**combinations[least_idx,1]) 
tem /= (data['거리']**combinations[least_idx,2]) 
tem *= np.exp(combinations[least_idx,4] * data['2019_y'] / data['전입지 면적'] * data['거리'])

result['mig19']= data['2019_x']
result['predict19']=tem
result.head

<bound method NDFrame.head of      mig17     predict17  mig18     predict18  mig19     predict19
0    19460   7954.762629  19737   7852.358790  20285   8579.420455
1     4506  10304.210328   4505  10054.005655   4220   9808.324627
2     2994   3016.665202   2902   2942.684938   3055   3012.400044
3     1073   2246.871795   1011   2161.343789    992   2107.626148
4     2159   2728.245268   2180   2618.268254   2172   2529.938475
..     ...           ...    ...           ...    ...           ...
267  13179  13184.711862  11989  12370.369744  11058  11977.113272
268  12426   8956.135944  11209   8399.980613  11334   8229.791870
269  12464   9562.767887  12017   9020.467630  11935   9085.623633
270  12692  10553.952408  11703  10015.934582  11369  10248.076461
271  10404   2710.352757   9829   2533.526360   8503   2380.941874

[272 rows x 6 columns]>

In [42]:

alpha = 0.810195923
beta = 0.807647705
gamma = 0.952972412
sig = -10.74194336
lamb = 0
combinations = np.array(np.meshgrid(alpha,beta,gamma, sig, lamb)).T.reshape(-1,5)
combinations

array([[  0.81019592,   0.80764771,   0.95297241, -10.74194336,
          0.        ]])

In [43]:
tem = 1
tem *= np.exp(combinations[least_idx,3])
tem *= (data['2020']**combinations[least_idx,0])
tem *= (data['2020_y']**combinations[least_idx,1]) 
tem /= (data['거리']**combinations[least_idx,2]) 
tem *= np.exp(combinations[least_idx,4] * data['2020_y'] / data['전입지 면적'] * data['거리'])

result['mig20']= data['2020_x']
result['predict20']=tem
result.head

<bound method NDFrame.head of      mig17     predict17  mig18     predict18  mig19     predict19  mig20  \
0    19460   7954.762629  19737   7852.358790  20285   8579.420455  20990   
1     4506  10304.210328   4505  10054.005655   4220   9808.324627   4674   
2     2994   3016.665202   2902   2942.684938   3055   3012.400044   2980   
3     1073   2246.871795   1011   2161.343789    992   2107.626148   1142   
4     2159   2728.245268   2180   2618.268254   2172   2529.938475   2144   
..     ...           ...    ...           ...    ...           ...    ...   
267  13179  13184.711862  11989  12370.369744  11058  11977.113272  11638   
268  12426   8956.135944  11209   8399.980613  11334   8229.791870  11210   
269  12464   9562.767887  12017   9020.467630  11935   9085.623633  11987   
270  12692  10553.952408  11703  10015.934582  11369  10248.076461  11647   
271  10404   2710.352757   9829   2533.526360   8503   2380.941874   9214   

        predict20  
0     8536.021380  
1    

In [44]:

alpha = 0.8306427
beta = 0.808486938
gamma = 0.936553955
sig = -11.15039063
lamb = 0
combinations = np.array(np.meshgrid(alpha,beta,gamma, sig, lamb)).T.reshape(-1,5)
combinations

array([[  0.8306427 ,   0.80848694,   0.93655396, -11.15039063,
          0.        ]])

In [45]:
tem = 1
tem *= np.exp(combinations[least_idx,3])
tem *= (data['2021']**combinations[least_idx,0])
tem *= (data['2021_y']**combinations[least_idx,1]) 
tem /= (data['거리']**combinations[least_idx,2]) 
tem *= np.exp(combinations[least_idx,4] * data['2021_y'] / data['전입지 면적'] * data['거리'])

result['mig21']= data['2021_x']
result['predict21']=tem
result.head

<bound method NDFrame.head of      mig17     predict17  mig18     predict18  mig19     predict19  mig20  \
0    19460   7954.762629  19737   7852.358790  20285   8579.420455  20990   
1     4506  10304.210328   4505  10054.005655   4220   9808.324627   4674   
2     2994   3016.665202   2902   2942.684938   3055   3012.400044   2980   
3     1073   2246.871795   1011   2161.343789    992   2107.626148   1142   
4     2159   2728.245268   2180   2618.268254   2172   2529.938475   2144   
..     ...           ...    ...           ...    ...           ...    ...   
267  13179  13184.711862  11989  12370.369744  11058  11977.113272  11638   
268  12426   8956.135944  11209   8399.980613  11334   8229.791870  11210   
269  12464   9562.767887  12017   9020.467630  11935   9085.623633  11987   
270  12692  10553.952408  11703  10015.934582  11369  10248.076461  11647   
271  10404   2710.352757   9829   2533.526360   8503   2380.941874   9214   

        predict20  mig21     predict21  
0   

In [46]:
result.to_csv('1grav.csv')